### ISSUE TITLE
Community Dashboard- All Questions Page UI design

### ISSUE THREAD

**Issue by kulkarni-prajakta-github** [LiamANeeson/MSc-Game-Engine-Project-Website#13]
Create UI component

**Comment by kulkarni-prajakta-github** [comment]
-Creation of dynamic grid for cards/questions
-Every post have tags, username, timestamp, views, likes and answers.

-In header section, add elements for filtering or search bar with autosense feature, filtering for sort
-Buttons for Asking question, filtering all/unanswered question
-Pagination for grid

**Comment by prajakta-kulkarni-git** [comment]
merged changes.Thank you
